### ISSUE TITLE
High CPU consumption using Coralogx hook with Logrus

### ISSUE THREAD

**Issue by elig-salt** [coralogix/go-coralogix-sdk#6]
Hi,
We've connected a hook to a logrus logger, and cpu spiked.
We've profiled and looks like Coralogix Go SDK is responsible for 95% of the CPU time.
Sending the bulk (23%) is understandable - but some 45% goes on formatting.
Can anyone on the Coralogix team advise?
This kind of spike is unacceptable on a client-side running app we're deploying.
Thanks.

![image (5)](https://user-images.githubusercontent.com/71209973/107407792-c5f9d500-6b12-11eb-957e-03ed44714998.png)

**Comment by EldarAliiev** [comment]
Thanks for the report!
We are investigating your issue.
What do you use for profiling and how much records do you send to Coralogix?

**Comment by elig-salt** [comment]
Thanks for the quick response.

### Reproducing:
We write a log every 5 seconds.
Just use logrus - and write logs every 5 seconds.
Then attach a coralogix web hook and see the cpu differences.

We do use fields, and sometimes not just strings
```go
log.WithFields(logrus.Fields{
	"hello": "world",
	"verisonDate": time.Now(),
}).Info("Hello World Message")
```

### Profiling:
1. go get -u github.com/google/pprof
2. Add this to your code:
```go
import  (
_ "net/http/pprof"
)

func RunProfiler() {
	go func() {
		log.Println(http.ListenAndServe("localhost:6060", nil))
	}()
}
```
and make sure to run RunProfiler() somewhere in your code, while keeping the process up.

3.
Run 
```sh
go tool pprof -http ":9000" -seconds 60 <SOME_RANDOM_NAME> http://localhost:6060/debug/pprof/profile
```
OR use the console (without the -http ":9000" part)
 
```sh
go tool pprof  -seconds 60 <SOME_RANDOM_NAME> http://localhost:6060/debug/pprof/profile
```
Then use commands such as: `top15`, `cum`, `flat`, etc.

**Comment by EldarAliiev** [comment]
We will check and get back to you ASAP.

**Comment by EldarAliiev** [comment]
We did profiling and benchmarking and cannot reproduce this behavior.
I'll update you when we'll find something else.

**Comment by elig-salt** [comment]
@EldarAliiev I've create a simple repo that reproduces this:
https://github.com/elig-salt/logrus-coralogix-cpu

**Comment by EldarAliiev** [comment]
@elig-salt I checked everything with profiler and even without any actions `go-coralogix-sdk.(*LoggerManager).Run` function takes ~99% of CPU time because it's running as goroutine in separate thread during all time of your program:

![1](https://user-images.githubusercontent.com/18129701/107679444-3df80480-6ca5-11eb-9d74-2ef96e02b83f.png)
![2](https://user-images.githubusercontent.com/18129701/107679549-5ec05a00-6ca5-11eb-90c5-4bacd43defe6.png)

**Comment by elig-salt** [comment]
Thanks for looking into this.
We appreciate it, and would like to be able to use Coralogix as a universal solution across our company.

Regarding your exaplanation -
Unfortunately - This still doesn't explain the radical spike in CPU.

In the original executable we ran when we saw this behavior - we run 7 additional goroutines, each with each own logic - http requests, files being watched, an actual web server, and more.
The CPU utilization on our side is less than 1%.

That's because a goroutine in itself is not CPU intensive.
Mutexes, loops and and thread synchronization actions, however, can be.

Here is a screenshot of some code I've added to the example I've shared before -
running 3 additional go-routines, each running a for loop - which will each utilize 100%:


![scr1](https://user-images.githubusercontent.com/71209973/107681958-6b927d00-6ca8-11eb-9259-2a70db7d1269.png)
![scr2](https://user-images.githubusercontent.com/71209973/107681969-6cc3aa00-6ca8-11eb-96b1-8cda6ddddc0b.png)
![scr3](https://user-images.githubusercontent.com/71209973/107681972-6df4d700-6ca8-11eb-9805-bff502034d6a.png)

Here is the same example without the loop:
![Screen Shot 2021-02-11 at 20 35 19](https://user-images.githubusercontent.com/71209973/107682212-b57b6300-6ca8-11eb-8e4d-ea1672bd9fc6.png)
![Screen Shot 2021-02-11 at 20 35 32](https://user-images.githubusercontent.com/71209973/107682218-b8765380-6ca8-11eb-88f5-f1d444c68cf5.png)

So - It's a question of what exactly is running in the goroutine, 
and not the fact the goroutine is running.

**Comment by EldarAliiev** [comment]
@elig-salt we added some fix.
Is this results works for you:
![1](https://user-images.githubusercontent.com/18129701/107972896-2aa6ab00-6fbd-11eb-99cd-cc267a1a5817.png)

**Comment by elig-salt** [comment]
Thanks for the effort.
I don't know how this affects CPU until I run the executable on the machine (the picture doesn't show what the executable will use as a percentage of the host machine - it only shows the CPU percentage out of whatever the binary uses).
So looking forward to seeing what changed in the next release of the SDK.
